修改地图参数: ze_obf_filth
fyscs/cs2 pull request #103
Opened 2024-02-17 11:19 UTC by YuQingMingran

## 该PR作用的地图是(仅英文小写)
ze_obf_filth
## 为什么要增加/修改这个东西
因该张地图属OBJ系列长征火星地图,地图流程约38分钟,并且该张地图有多个地点人类需要分双路进行防守,压力可能较大,故增加三种手雷数量。目前CS2环境萌新偏多,需要更多地图时间来让萌新熟悉地图,故增加地图VIP投票和地图时长，并且该张地图有地图特色加血站,故删除血针,考虑该张地图流程过长,道具不能过于稀少,故增强僵尸击退至0.8击退。
## 在提交PR前请确认已完成以下工作
- 我已经阅读了``OP手册`` 和 ``参数修改公约``.
- 我已经遵守了手册和公约的指导.
- 我已经自检过以确认没有错误的符号拼写和非法字符.
- 我已经按照公约的要求正确填写PR的标题.
- 我在提交PR前已将分支更新到最新.
- 我确认该PR中仅包含一张地图的内容.

2024-02-17 22:04 UTC, Kxnrl requested changes

2024-02-17 22:04 UTC, Kxnrl commented on 2001/csgo/cfg/map-configs/ze_obf_filth.cfg
> +ze_weapons_spawn_decoy "1"
你说了提高上限, 而不是开局就发

2024-02-18 02:27 UTC, YuQingMingran commented on 2001/csgo/cfg/map-configs/ze_obf_filth.cfg
> +ze_weapons_spawn_decoy "1"
了解了解.

2024-02-18 12:58 UTC, Kxnrl approved these changes

2024-02-18 12:58 UTC, merged