补充地图参数: ze_tkara_p
fyscs/cs2 pull request #69
Opened 2024-01-18 15:16 UTC by Suancaiyuzy1

## 该PR作用的地图是(仅英文小写)
ze_tkara_p
## 为什么要增加/修改这个东西
补充地图: ze_tkara_p 的CFG参数文件
## 在提交PR前请确认已完成以下工作
- 我已经阅读了``OP手册`` 和 ``参数修改公约``.
- 我已经遵守了手册和公约的指导.
- 我已经自检过以确认没有错误的符号拼写和非法字符.
- 我已经按照公约的要求正确填写PR的标题.
- 我在提交PR前已将分支更新到最新.
- 我确认该PR中仅包含一张地图的内容.

2024-01-19 01:49 UTC, Kxnrl requested changes

2024-01-19 01:49 UTC, Kxnrl commented on 2001/csgo/cfg/map-configs/ze_tkara_p.cfg
> +mp_timelimit "40.0"
请说明为什么给这么长时间

2024-01-19 07:01 UTC, Suancaiyuzy1 commented on 2001/csgo/cfg/map-configs/ze_tkara_p.cfg
> +mp_timelimit "40.0"
本张地图流程在10分钟左右，且守点较为紧凑，稍有失误可能会导致重新开局，故设置40分钟

2024-01-21 01:46 UTC, Kxnrl commented on 2001/csgo/cfg/map-configs/ze_tkara_p.cfg
> +mp_timelimit "40.0"
你流程10分钟图, 为什么要把地图时间40分钟?

2024-01-22 16:30 UTC, Kxnrl approved these changes

2024-01-22 16:31 UTC, merged