修改地图参数: ze_paycheck_p
fyscs/cs2 pull request #75
Opened 2024-01-27 07:09 UTC by Suancaiyuzy1

## 该PR作用的地图是(仅英文小写)
ze_paycheck_p
## 为什么要增加/修改这个东西
地图流程过短，为防止连续尸变，所以将指数尸变改为随机尸变，且减少地图时间以及延长投票次数
## 在提交PR前请确认已完成以下工作
- 我已经阅读了``OP手册`` 和 ``参数修改公约``.
- 我已经遵守了手册和公约的指导.
- 我已经自检过以确认没有错误的符号拼写和非法字符.
- 我已经按照公约的要求正确填写PR的标题.
- 我在提交PR前已将分支更新到最新.
- 我确认该PR中仅包含一张地图的内容.

2024-01-27 14:24 UTC, Kxnrl commented on 2001/csgo/cfg/map-configs/ze_paycheck_p.cfg
> -mp_timelimit "25.0"
?

2024-01-27 14:24 UTC, Kxnrl requested changes

2024-01-27 14:24 UTC, Kxnrl commented on 2001/csgo/cfg/map-configs/ze_paycheck_p.cfg
> +mp_timelimit "10.0"
?

2024-01-27 16:05 UTC, Suancaiyuzy1 commented on 2001/csgo/cfg/map-configs/ze_paycheck_p.cfg
> +mp_timelimit "10.0"
平均2分钟一局，故把该时间下调

2024-01-30 07:53 UTC, Kxnrl commented
地图时间过短

2024-01-30 07:53 UTC, closed without merging