修改地图参数: ze_obj_rampage_v1_2
fyscs/cs2 pull request #82
Opened 2024-02-02 12:11 UTC by YuQingMingran

## 该PR作用的地图是(仅英文小写)
ze_obj_rampage_v1_2
## 为什么要增加/修改这个东西
目前CS2萌新偏多，地图流程过长，执行力过差，导致人类胜利略困难，参考CSGO中地图的参数进行修改。
## 在提交PR前请确认已完成以下工作
- 我已经阅读了``OP手册`` 和 ``参数修改公约``.
- 我已经遵守了手册和公约的指导.
- 我已经自检过以确认没有错误的符号拼写和非法字符.
- 我已经按照公约的要求正确填写PR的标题.
- 我在提交PR前已将分支更新到最新.
- 我确认该PR中仅包含一张地图的内容.

2024-02-13 07:33 UTC, Kxnrl requested changes
无合理理由同时提高VIP/MCR投票

2024-02-14 09:20 UTC, Kxnrl commented on 2001/csgo/cfg/map-configs/ze_obj_rampage_v1_2.cfg
> +ze_knockback_scale "0.7"
?

2024-02-14 09:22 UTC, Kxnrl requested changes

2024-02-14 09:22 UTC, Kxnrl commented on 2001/csgo/cfg/map-configs/ze_obj_rampage_v1_2.cfg
> +ze_knockback_scale "0.7"
?

2024-02-14 09:49 UTC, YuQingMingran commented on 2001/csgo/cfg/map-configs/ze_obj_rampage_v1_2.cfg
> +ze_knockback_scale "0.7"
这个参数我是依据CSGO中当前地图来进行参考,修改，原CSGO中参数为0,8，考虑到人类目前CS2手雷过于强大,该张地图全流程大概为38分钟，人类道具量过少的话,游戏中后期会严重缺乏道具,故而改为0.7平衡一下双方差距。

2024-02-14 19:39 UTC, Kxnrl approved these changes

2024-02-14 19:40 UTC, merged